### ISSUE TITLE
StaticMethodTransformTest.testStaticAdviceTransformer() test failed

### ISSUE THREAD

**Issue by jxd134** [megaease/easeagent#157]
https://github.com/megaease/easeagent/blob/8f49b87c511a2b83719c783e83fc0b2bf640d252/core/src/test/java/com/megaease/easeagent/core/instrument/StaticMethodTransformTest.java#L97-L99

![图片](https://user-images.githubusercontent.com/14814212/147331517-66910445-4f8a-4037-b9ab-e76e22a50714.png)

**Comment by Oseenix** [comment]
Pass on Windows-lastest with JDK 8/11/16(OpenJDK-hs-adpt) and JDK 8/11(OpenJDK-j9-adpt). 
But there is another unit test fail on Windows-lastest(Win-Server-2019) with OpenJ9-16.02 on GitHub action, and it can't be reproduced on our windows(Win-Server-2019) environment with the same JDK.
We will continue to look at what the problem is.
